### ISSUE TITLE
Any hint or doc to list all APIs supported in tgi-gaudi?

### ISSUE THREAD

**Issue by Ruoyu-y** [huggingface/tgi-gaudi#132]
I tried the api supported in tgi main branch '/v1/completions' on gaudi-tgi instance and found no response.
Any place to find the APIs that is currently available in tgi-gaudi?

**Comment by regisss** [comment]
Can you link to '/v1/completions' please? I cannot find it anywhere.

**Comment by Ruoyu-y** [comment]
> Can you link to '/v1/completions' please? I cannot find it anywhere.

It is listed in the TGI API documentation here https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/completions

**Comment by regisss** [comment]
This was added in TGI v1.3 and we are going to support it soon.
There might be a bit of latency at times between releases of TGI and the moment we catch up on Gaudi.

**Comment by kdamaszk** [comment]
@Ruoyu-y tgi-gaudi is aligned with TGI 2.0 now, so you can use both '/v1/completions' and '/v1/chat/completions' calls. Please let us know if you will find any issues with this
