### ISSUE TITLE
LlaVa support

### ISSUE THREAD

**Issue by JoeyTPChou** [huggingface/tgi-gaudi#149]
### Model description

https://github.com/huggingface/text-generation-inference/pull/1709
Since the TGI has done the LlaVa support. Would like to know if there is any timeline for the LlaVa support on TGI Gaudi

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://github.com/huggingface/text-generation-inference/pull/1709

**Comment by kdamaszk** [comment]
@regisss @libinta do we have any timeline about LlaVa support?

**Comment by libinta** [comment]
@Karol ***@***.***> llava is supported from optimum-habana main already. It will be on v1.12.0

**Comment by regisss** [comment]
Llava-next support was added in https://github.com/huggingface/tgi-gaudi/pull/187.
